site_name: Template MkDocs
docs_dir: docs

nav:
  - Conteúdo: index.md
  - Nova Página: new_page.md

theme:
  name: material
  language: pt-BR
  favicon: public/favicon.svg
  icon:
    logo: fontawesome/solid/file-code
    repo: fontawesome/brands/github
    annotation: material/arrow-right-circle

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  font:
    text: Lato
    code: "JetBrains Mono"

  features:
    - navigation.top # Mostra a barra de navegação no topo da página
    - navigation.indexes # Adiciona uma página de índices de navegação
    - navigation.footer # Adiciona links no rodapé
    - content.code.annotate # Permite anotar linhas de código
    - toc.integrate # Integra a tabela de conteúdos na barra lateral
    - header.autohide # Esconde o cabeçalho ao rolar para baixo
    - search.suggestions # Sugestões de pesquisa
    - search.highlight # Destaque de pesquisa
    - search.shared # Pesquisa compartilhada
    - navigation.tabs # Adiciona abas de navegação

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: false
  - pymdownx.inlinehilite
  - pymdownx.keys:
      key_map:
        click: "Click"
        left-click: "Left Click"
        right-click: "Right Click"
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - tables

plugins:
  - search
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     fallback_to_build_date: true
  - glightbox

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  analytics:
    provider: google
    property: G-RS6649M9GY #TODO: substituir pelo ID pessoal / mover para variáveis de ambiente
  consent:
    title: "Aceitar os cookies"
    description: >-
      Utilizamos cookies para melhorar sua experiência e analisar o uso
      da documentação. :)
